### ISSUE TITLE
UnknownFS problem

### ISSUE THREAD

**Issue by tanitsu721** [gus33000/MobilePackageGen#2]
Whenever I try get the cab files from my mobile ffu, MainOS partition get recognised as unknown while it is in its correct filesystem.

**Comment by gus33000** [comment]
Hi we would need more information namely:

- The ffu file in question
- The operating system type and version your host uses (windows build 22621, macOS big sur, linux 6.5 Ubuntu etc)
- the version of the tool you use
- the command you use

**Comment by gus33000** [comment]
Hello?

We would need the information above, otherwise we will have to consider this issue closed after 4 days.

**Comment by gus33000** [comment]
Issue closed as no response was provided
