### ISSUE TITLE
there might be a bug in method GetFilesWithNtfsIssueWorkaround that prevents all results from being found when searching for files.

### ISSUE THREAD

**Issue by BlueRain-debug** [gus33000/MobilePackageGen#4]
I performed IEnumerable<string> manifestFiles = fileSystem.GetFilesWithNtfsIssueWorkaround(@"Windows\servicing\Packages", "*.cat", SearchOption.TopDirectoryOnly); and manifestFiles = fileSystem.GetFilesWithNtfsIssueWorkaround(@"Windows\servicing\Packages", "*.mum", SearchOption.TopDirectoryOnly); on the same vhd image with 162 files (cat and mum) in the servicing\Packages folder. For the former I got a return result of {string[80]}, and for the latter I got a return result of {string[43]}.
The expected output of both methods should be {string[81]}, so I think this may be a bug, but I haven't found the reason yet.

**Comment by gus33000** [comment]
We are working around a discutils issue here. It would be nice to have said vhd intact for further data analysis as there's an underlying bug in the NTFS code on discutils side.

**Comment by gus33000** [comment]
I cannot add the missing information tag from my phone but I'll be waiting for the file to help trouble shoot this further

**Comment by gus33000** [comment]
Without the required further information we are forced to close this issue within a 4 days window from the notice (label being added).

We would like to thank you for the report nonetheless but we cannot go forward with your issue report without the requested information

**Comment by gus33000** [comment]
Without the required further information we are forced to close this issue within a 1 day window from the notice (label being added so 4 days total).

We would like to thank you for the report nonetheless but we cannot go forward with your issue report without the requested information
