### ISSUE TITLE
Data missing from packages

### ISSUE THREAD

**Issue by tanitsu721** [gus33000/MobilePackageGen#5]
After generating the cabs from a Windows mobile-based FFU, some of the data is missing from the packages. Found this issue while building the OS. The data seems to be corrupted but the FFU isn't corrupted.

**Host**: 19045.4894
**ADK Version**: 18362.1
**Image**:

![image](https://github.com/user-attachments/assets/b60efbd1-0ed4-48c8-93f4-7bc24b9d8bb0)
While the data seems to be there:
![image](https://github.com/user-attachments/assets/84197454-e3e6-417e-9f38-68cfe36370f1)

**Comment by gus33000** [comment]
This is not a problem with MobilePackageGen but rather the tool youre using making use of said cabinet file. It is complaining it cannot find the file at the path it is printing. Recheck your environment, anyway its not this tool problem. But your filename very likely is not correct at all or the tool youre using is broken or not intended to work with this.

**Comment by tanitsu721** [comment]
I used the tool for what it was intended. I converted a FFU without OSPool.

**Comment by gus33000** [comment]
And the issue you are posting about is not an issue in MobilePackageGen but secondary software. It is therefore not a bug with MobilePackageGen and this issue is closed as a result.

**Comment by tanitsu721** [comment]
DM me, I will explain whats the problem. Discord username: wcostest.

**Comment by gus33000** [comment]
You can post details on github. This is an open source project and you can be free to provide information on here. As your issue stands right now, its clear the crash you are reporting is an issue with your filenames and / or imageapp itself. Both of which, this tool does not deal with.

**Comment by tanitsu721** [comment]
So the problem is that I converted Andromeda 17686 ffu into cbs (using the latest release) for testing purposes. The conversion was successful but when used against imageapp, the data seems to be invalid.

**Comment by gus33000** [comment]
This still isnt an issue with MobilePackageGen. Specific builds need to be built using the very same version of the ADK as the build itself.

Further more above you showed "17110" not "17686" and you used imageapp 18262. this wont ever work. And it remains not an issue with MobilePackageGen.

MobilePackageGen only does one thing, generate you cabinet files out of an image. Whenever or not you can build it using incorrect software is not the tool responsibility.
