### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by tanitsu721** [gus33000/MobilePackageGen#6]
Please add the support for building the cabs from a regular ffu as well

**Comment by gus33000** [comment]
That functionality is already supported.

Read the readme, it is the example we give from the very start as well.

**Comment by tanitsu721** [comment]
I meant from regular Windows 10 FFUs

**Comment by gus33000** [comment]
The FFU file format is no different and this is already supported. Both V1 V1_COMPRESSED and V2 are supported.

**Comment by tanitsu721** [comment]
Ok thanks for the info
