### ISSUE TITLE
Bug: MobilePackageGen ignores files from regular ffus

### ISSUE THREAD

**Issue by tanitsu721** [gus33000/MobilePackageGen#7]
As @gus33000 said that it has the support for generation of cab files from Non-mobile/wcos image, but the program simply ignores the creation of files and skips them. The image is not built from OEMInput files. Its an ARMv7 Image

**Comment by gus33000** [comment]
I haven't said that the tool was meant to work with Windows Desktop. In the issue you previously made you asked if it was compatible with "normal ffus", as in, the FFU format used by dism and others, to which I replied yes it is. And that is true. It is however not meant to do anything with non mobile layouts. And this won't be added.
